import psycopg2
import sys

# PostgreSQL Database Connection Config
DB_CONFIG = {
    "dbname": "postgres",  # Update with your DB Name
    "user": "postgres",  # Update with your DB Username
    "password": "sharma30@",  # Update with your DB Password
    "host": "localhost",
    "port": "5432"
}


def fetch_postgresql_report():
    """Connects to PostgreSQL and fetches QBER statistics generated by C++."""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()
        print("[+] PyCharm connected to PostgreSQL successfully.")
    except Exception as e:
        print(f"[-] Database connection failed: {e}")
        sys.exit(1)

    print("\n" + "=" * 80)
    print("      POSTGRESQL STATISTICAL ANALYSIS REPORT (GENERATED FROM C++ DATA)     ")
    print("=" * 80)

    # Query SQL View
    cursor.execute("""
                   SELECT eve_rate,
                          total_trials,
                          avg_sifted_length,
                          avg_qber,
                          stddev_qber,
                          detection_accuracy_pct
                   FROM qkd_detection_stats;
                   """)

    rows = cursor.fetchall()

    if not rows:
        print("[-] No data found in PostgreSQL. Run C++ script in CLion first!")
        return

    header = f"{'Eve Rate':<10} | {'Trials':<8} | {'Avg Key Len':<12} | {'Avg QBER':<10} | {'StdDev QBER':<12} | {'Eve Detection %':<15}"
    print(header)
    print("-" * len(header))

    for row in rows:
        eve_rate, trials, avg_len, avg_qber, stddev_qber, det_acc = row
        print(
            f"{eve_rate:<10.1f} | {trials:<8} | {avg_len:<12.1f} | {avg_qber:<10.4f} | {stddev_qber:<12.4f} | {det_acc:<15.2f}%")

    print("=" * 80 + "\n")

    cursor.close()
    conn.close()


if __name__ == "__main__":
    fetch_postgresql_report()